"""
Add config

Revision ID: 25c2f04fd589
Revises: fab151c03416
Create Date: 2024-07-10 05:31:29.698662
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "25c2f04fd589"
down_revision: Union[str, None] = "fab151c03416"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "chatgpt_key",
            sa.Text(),
            nullable=False,
            comment="The ChatGPT API key",
        ),
        sa.Column(
            "model",
            sa.Text(),
            nullable=False,
            comment="The model to use for the ChatGPT",
        ),
        sa.Column(
            "pages_concurrency",
            sa.Integer(),
            nullable=False,
            comment="The number of concurrent pages to scrape",
        ),
        sa.Column(
            "products_concurrency",
            sa.Integer(),
            nullable=False,
            comment="The number of concurrent products to scrape",
        ),
        sa.Column(
            "required",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The required fields for the product",
        ),
        sa.Column(
            "not_reprocess",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The fields that should not be reprocessed",
        ),
        sa.Column(
            "description_prompt",
            sa.Text(),
            nullable=False,
            comment="The prompt for the description",
        ),
        sa.Column(
            "keywords_prompt",
            sa.Text(),
            nullable=False,
            comment="The prompt for the keywords",
        ),
        sa.Column(
            "properties_prompt",
            sa.Text(),
            nullable=False,
            comment="The prompt for the properties",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_config")),
    )
    op.alter_column(
        "product",
        "url",
        existing_type=sa.TEXT(),
        comment="The URL of the product",
        existing_comment="The hash of the product",
        existing_nullable=False,
    )
    op.alter_column(
        "product",
        "hash",
        existing_type=sa.TEXT(),
        comment="The hash of the product",
        existing_comment="The URL of the product",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "hash",
        existing_type=sa.TEXT(),
        comment="The URL of the product",
        existing_comment="The hash of the product",
        existing_nullable=False,
    )
    op.alter_column(
        "product",
        "url",
        existing_type=sa.TEXT(),
        comment="The hash of the product",
        existing_comment="The URL of the product",
        existing_nullable=False,
    )
    op.drop_table("config")
    # ### end Alembic commands ###
