"""
XLSX

Revision ID: df364bdbd6e1
Revises: e1be18a8b485
Create Date: 2024-07-12 15:24:40.807995
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "df364bdbd6e1"
down_revision: Union[str, None] = "e1be18a8b485"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "xlsx_source",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "filename",
            sa.Text(),
            nullable=False,
            comment="The name of the file",
        ),
        sa.Column(
            "minio_uuid",
            sa.UUID(as_uuid=False),
            nullable=True,
            comment="The UUID of the file in the MinIO storage",
        ),
        sa.Column(
            "column_mapping",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="The mapping between the file columns and the Satu fields",
        ),
        sa.Column(
            "last_processed",
            sa.DateTime(),
            nullable=True,
            comment="The last time the file was processed",
        ),
        sa.Column(
            "state",
            sa.Enum(
                "CREATED",
                "PROCESSING",
                "DATA_PENDING_APPROVAL",
                "FINISHED",
                "EXPORTING",
                "EXPORTED",
                name="excelsourcestate",
            ),
            nullable=False,
            comment="The FSM state of the Excel source",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xlsx_source")),
    )
    op.drop_table("file_source")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_source",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "minio_uuid",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment="The UUID of the file in the MinIO storage",
        ),
        sa.Column(
            "file_type",
            postgresql.ENUM("CSV", "XLSX", "PDF", name="filetype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "file_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="The metadata of the file used to transform the data",
        ),
        sa.Column(
            "last_processed",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="The last time the file was processed",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_file_source"),
    )
    op.drop_table("xlsx_source")
    # ### end Alembic commands ###
