"""
Add reprocessing

Revision ID: e1be18a8b485
Revises: 25c2f04fd589
Create Date: 2024-07-10 06:39:53.763160
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "e1be18a8b485"
down_revision: Union[str, None] = "25c2f04fd589"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "reprocessing",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="Whether the product is being reprocessed",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "reprocessing")
    # ### end Alembic commands ###
