"""
initial

Revision ID: fab151c03416
Revises:
Create Date: 2024-06-26 19:32:44.348046
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fab151c03416"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_source",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "minio_uuid",
            sa.UUID(as_uuid=False),
            nullable=True,
            comment="The UUID of the file in the MinIO storage",
        ),
        sa.Column(
            "file_type",
            sa.Enum("CSV", "XLSX", "PDF", name="filetype"),
            nullable=False,
        ),
        sa.Column(
            "file_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="The metadata of the file used to transform the data",
        ),
        sa.Column(
            "last_processed",
            sa.DateTime(),
            nullable=True,
            comment="The last time the file was processed",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_source")),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "hash",
            sa.Text(),
            nullable=False,
            comment="The URL of the product",
        ),
        sa.Column(
            "url",
            sa.Text(),
            nullable=False,
            comment="The hash of the product",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="The data of the product for Satu.kz",
        ),
        sa.Column(
            "last_processed",
            sa.DateTime(),
            nullable=True,
            comment="The last time the product was processed",
        ),
        sa.Column(
            "source_id",
            sa.UUID(as_uuid=False),
            nullable=True,
            comment="The UUID of the source",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("hash", name=op.f("uq_product_hash")),
    )
    op.create_table(
        "website_source",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "contents",
            sa.Text(),
            nullable=True,
            comment="The contents of the website",
        ),
        sa.Column("name", sa.Text(), nullable=True, comment="Website title"),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Website meta description",
        ),
        sa.Column("favicon", sa.Text(), nullable=True, comment="Website favicon"),
        sa.Column(
            "product_regex",
            sa.Text(),
            nullable=True,
            comment="Regex that matches the product URLs on the website",
        ),
        sa.Column(
            "pagination_regex",
            sa.Text(),
            nullable=True,
            comment="Regex that matches the pagination URLs on the website",
        ),
        sa.Column(
            "props_xpaths",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Mapping between the website properties and the XPATHs",
        ),
        sa.Column(
            "state",
            sa.Enum(
                "CREATED",
                "UNAVAILABLE",
                "SCRAPED",
                "XPATHS_PENDING",
                "XPATHS_READY",
                "DATA_COLLECTING",
                "DATA_PENDING_APPROVAL",
                "FINISHED",
                "EXPORTING",
                "EXPORTED",
                name="websitesourcestate",
            ),
            nullable=False,
            comment="The FSM state of the website source",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_website_source")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("website_source")
    op.drop_table("product")
    op.drop_table("file_source")
    op.execute("DROP TYPE filetype")
    op.execute("DROP TYPE websitesourcestate")
    # ### end Alembic commands ###
