name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    env:
      SKIP: no-commit-to-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
      - name: Install dependencies
        run: poetry install --with=prefect --with=dev --with=backend
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile
      - uses: pre-commit/action@v3.0.0
